### PR TITLE
Google kick start

### PR DESCRIPTION
**Pull request by mohammadasad9450**
this is an important problem and was asked in Google kick start.
Merge asap.

### CODE REVIEW

**Comment by pratyushmp** [comment]
Feel free to contribute more such problems!

**Comment by mohammadasad9450** [comment]
bro your repository is showing invalid in Hacktoberfest

**Comment by pratyushmp** [comment]
Yeah it happened 2 days back :(. But the repo still has good collection of code!

**Comment by mohammadasad9450** [comment]
Why bro sad to hear??Have u received any hactoberfest tshirt please tell me
about ur experience

**Comment by pratyushmp** [comment]
Yeah I participated in Hacktoberfest last year too, and the experience has been good, learnt a lot of things along the way. After the maturity period is over you will get link to upload the shipping address and then you will get a tracking number to track your package.

**Comment by mohammadasad9450** [comment]
Bro please give ur facebook id
 and write git i want to talk to u I am very excited can u tell when did u
received the t how it was

**Comment by mohammadasad9450** [comment]
when did u received the tshirt after how many days?

**Pull request merged**
