### PR TITLE
Using dictionary to count the frequency of letters in the input string

### LINKED ISSUE #150: Add Codes in the language of your choice :)

### PR DESCRIPTION
**Pull request by LON3WO7F**
Using a dictionary to count the frequency of letters in a sentence.
closes #150

### CODE REVIEW

**Comment by LON3WO7F** [comment]
@pratyushmp  Please review my PR.

**Review by pratyushmp — APPROVED** [review]

**Comment by LON3WO7F** [comment]
Screenshot
Hey @pratyushmp 
This is showing me **Ineligible Repository ** sign.
What does it mean?

**Comment by pratyushmp** [comment]
Your commit to This repo will now no longer be counted for Hacktoberfest!

**Comment by pratyushmp** [comment]
I just got the Message from Digital Ocean

**Comment by LON3WO7F** [comment]
Why?

**Comment by LON3WO7F** [comment]
> Your commit to This repo will now no longer be counted for Hacktoberfest!

@pratyushmp  Why?

**Comment by pratyushmp** [comment]
Sometimes when a lot people contribute to a repo, they think that the repo is a spam. SO they do it

**Comment by LON3WO7F** [comment]
Please include **hacktoberfest-accepted** label.

**Pull request merged**
