### PR TITLE
Deno language snippet + sample server creating script using TypeScript in Deno

### PR DESCRIPTION
**Pull request by immayurpanchal**
This snippet will help in understanding how to write Hello World using Deno language and also server creation using deno which is written in TypeScript. Though Deno support Javascript and Typescript both. 

@pratyushmp , Please add required labels of hacktoberfest.

Thanks a lot for this. I'll learn Deno while contributing to this repo.

### CODE REVIEW

**Comment by pratyushmp** [comment]
Sure...Looks very interesting. Keep contributing :)

**Comment by immayurpanchal** [comment]
@pratyushmp, I would love to contribute more. My PR seems not to be eligible for hacktoberfest. maybe because lables are missing. Kindly help here.

Screenshot from 2020-10-04 00-12-20


Screenshot from 2020-10-04 00-12-29

**Comment by pratyushmp** [comment]
No it's not because of the labels. It's just that during this hacktoberfest, people have been making a lot of PR's to my repo so digital ocean thinks that it's a spam. So they made this repo ineligible for hacktoberfest :(  Happened 2 days back

**Comment by immayurpanchal** [comment]
@pratyushmp , Oh, I see. Can you please try by adding labels to my PR as shown in the below screenshot? Maybe that may can help here.

Screenshot from 2020-10-04 17-31-26

**Comment by pratyushmp** [comment]
Done. I don't think it will work. Check now

**Comment by immayurpanchal** [comment]
@pratyushmp , I would love to contribute more to this Project. Can you please confirm whether this project is considered as spam by DigitalOcean now or the spam issue will be resolved soon because as you informed this is the issue because of lots of PR you are getting.

**Comment by pratyushmp** [comment]
I have no clue to be honest. I guess we will just have to wait and see what happens.

**Comment by immayurpanchal** [comment]
@pratyushmp , No problem. Thanks for your efforts. Though while investigating I have found one difference between all my other PRs and this PR which is current project doesn't have any labels assigned of hacktoberfest. Can you please give a last try by applying labels to the project itself. 

Please check attached screenshot for more clarity (Right side about section of the project)

Screenshot from 2020-10-04 17-58-16
Screenshot from 2020-10-04 17-57-53

**Comment by pratyushmp** [comment]
Done

**Pull request merged**
